# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Preload Domain Library"""

from typing import Any, Dict, Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...ModCDPClient import ModCDPClient

class PreloadClient:
    """Client for Preload domain commands."""

    def __init__(self, client: 'ModCDPClient'):
        self._client = client

    def enable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        return cast("Dict[str, Any]", self._client.send_raw(
            method="Preload.enable",
            params=params,
            session_id=session_id,
        ))

    def disable(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "Dict[str, Any]":
        return cast("Dict[str, Any]", self._client.send_raw(
            method="Preload.disable",
            params=params,
            session_id=session_id,
        ))
