# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP FileSystem Domain Library"""

from typing import Optional, cast

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...ModCDPClient import ModCDPClient
    from .commands import GetDirectoryParameters
    from .commands import GetDirectoryReturns

class FileSystemClient:
    """Client for FileSystem domain commands."""

    def __init__(self, client: 'ModCDPClient'):
        self._client = client

    def getDirectory(
        self,
        params: "GetDirectoryParameters",
        session_id: Optional[str] = None,
    ) -> "GetDirectoryReturns":
        return cast("GetDirectoryReturns", self._client.send_raw(
            method="FileSystem.getDirectory",
            params=params,
            session_id=session_id,
        ))
