#!/usr/bin/env node
// MODCDP_TRANSLATE: KEEP THIS FILE TRANSLATED ACROSS TYPESCRIPT, PYTHON, AND GO.
// Keep all shapes, signatures, behavior, and tests 1:1 in sync with:
// - ./python/modcdp/types/codegen.py
// - ./go/modcdp/types/codegen.go

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const generated_dir = path.join(here, "generated");
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "modcdp-protocol-"));
const existing_cdp = fs.existsSync(path.join(generated_dir, "cdp.ts"))
  ? fs.readFileSync(path.join(generated_dir, "cdp.ts"), "utf8")
  : "";
const protocol_version = existing_cdp.match(/devtools-protocol@([^.\s]+(?:\.[^.\s]+)*)/)?.[1] || "latest";
const meta = await fetch(`https://registry.npmjs.org/devtools-protocol/${protocol_version}`).then((r) => r.json());
const tgz = path.join(tmp, "devtools-protocol.tgz");
fs.writeFileSync(tgz, Buffer.from((await fetch(meta.dist.tarball).then((r) => r.arrayBuffer())) as ArrayBuffer));
execFileSync("tar", ["-xzf", tgz, "-C", tmp]);

const pkg = path.join(tmp, "package");
const domains = ["json/js_protocol.json", "json/browser_protocol.json"]
  .flatMap((file) => JSON.parse(fs.readFileSync(path.join(pkg, file), "utf8")).domains || [])
  .sort((a, b) => a.domain.localeCompare(b.domain));

const word = (x) => (/^[$A-Z_a-z][$\w]*$/.test(x) ? x : JSON.stringify(x));
const safe = (x) => x.replaceAll(/[^A-Z_a-z0-9]/g, "_").replace(/^(\d)/, "_$1");
const title = (x) => (x ? x[0].toUpperCase() + x.slice(1) : x);
const params = (x) => `${title(x)}Params`;
const result = (x) => `${title(x)}Result`;
const event = (x) => `${title(x)}Event`;
const domain_file = (d) => safe(d);
const local_name = (x) => safe(x);

const zexpr = (x, d) => {
  if (!x) return "z.unknown()";
  if (x.$ref) {
    const [rd, rn] = x.$ref.includes(".") ? x.$ref.split(".", 2) : [d, x.$ref];
    return `z.lazy(() => ${rd === d ? local_name(rn) : `${domain_file(rd)}.${local_name(rn)}`})`;
  }
  if (x.enum) return x.enum.length ? `z.enum([${x.enum.map(JSON.stringify).join(", ")}])` : "z.string()";
  if (x.type === "array") return `z.array(${zexpr(x.items, d)})`;
  if (x.type === "object") return x.properties?.length ? zobj(x.properties, d) : "z.record(z.string(), z.unknown())";
  if (x.type === "integer") return "z.number().int()";
  if (x.type === "number") return "z.number()";
  if (x.type === "boolean") return "z.boolean()";
  if (x.type === "any") return "z.any()";
  return "z.string()";
};

const zobj = (xs: any[] = [], d: string) =>
  `z.object({ ${xs.map((x) => `${JSON.stringify(x.name)}: ${zexpr(x, d)}${x.optional ? ".optional()" : ""}`).join(", ")} }).passthrough()`;
const collect_refs = (x, d, refs) => {
  if (!x) return;
  if (x.$ref) {
    const [rd] = x.$ref.includes(".") ? x.$ref.split(".", 2) : [d, x.$ref];
    if (rd !== d) refs.add(rd);
  }
  if (x.items) collect_refs(x.items, d, refs);
  for (const p of x.properties || []) collect_refs(p, d, refs);
  for (const p of x.parameters || []) collect_refs(p, d, refs);
  for (const p of x.returns || []) collect_refs(p, d, refs);
};
const modcdpTypes = [
  ...fs.readFileSync(path.join(here, "modcdp.ts"), "utf8").matchAll(/^type ModCDP([A-Z]\w*)\s*=/gm),
].map((match) => ({ name: match[1], type: `ModCDP${match[1]}` }));

const emitCdpNamespace = (lines, indent = "") => {
  for (const d of domains) {
    lines.push(`${indent}export namespace ${d.domain} {`);
    for (const x of d.types || [])
      lines.push(`${indent}  export type ${x.id} = z.infer<typeof zod.${d.domain}.${word(x.id)}>;`);
    for (const x of d.commands || []) {
      lines.push(`${indent}  export type ${params(x.name)} = z.infer<typeof zod.${d.domain}.${word(params(x.name))}>;`);
      lines.push(`${indent}  export type ${result(x.name)} = z.infer<typeof zod.${d.domain}.${word(result(x.name))}>;`);
    }
    for (const x of d.events || [])
      lines.push(`${indent}  export type ${event(x.name)} = z.infer<typeof zod.${d.domain}.${word(event(x.name))}>;`);
    lines.push(`${indent}}`);
  }
};

const emitModCDPNamespace = (lines, indent = "") => {
  lines.push(`${indent}export namespace Mod {`);
  for (const x of modcdpTypes) lines.push(`${indent}  export type ${x.name} = ${x.type};`);
  lines.push(`${indent}}`);
};

const cdp = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `import { zod, commands, events, types as runtimeTypes } from "./zod.js";`,
  `import type { z } from "zod";`,
  `import type { ${modcdpTypes.map((x) => x.type).join(", ")} } from "../modcdp.js";`,
  ``,
  `export const REQUEST = "request" as const;`,
  `export const RESPONSE = "response" as const;`,
  `export const EVENT = "event" as const;`,
  ``,
  `export { zod, commands, events };`,
  `export type CdpRuntime = {`,
  `  readonly types: typeof runtimeTypes;`,
  `  readonly commands: typeof commands;`,
  `  readonly events: typeof events;`,
  `  readonly REQUEST: typeof REQUEST;`,
  `  readonly RESPONSE: typeof RESPONSE;`,
  `  readonly EVENT: typeof EVENT;`,
  `};`,
  `export const cdp: CdpRuntime = { types: runtimeTypes, commands, events, REQUEST, RESPONSE, EVENT };`,
  `export const types: typeof runtimeTypes = cdp.types;`,
  ``,
  `export namespace cdp {`,
  `  export namespace types {`,
  `    export namespace ts {`,
];
emitModCDPNamespace(cdp, "      ");
emitCdpNamespace(cdp, "      ");
cdp.push(`    }`, `  }`, `}`, ``);

const aliases = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `import type { z } from "zod";`,
  `import type { cdp } from "./cdp.js";`,
  `import { commands, events, types as runtimeTypes } from "./zod.js";`,
  `import { Mod, normalizeModCDPName, validateZodSchema } from "../modcdp.js";`,
  `import type { ProtocolParams, ProtocolPayload, ProtocolResult } from "../modcdp.js";`,
  ``,
  `export type CdpNamedValue<Name extends string = string, Kind extends string = string> = { readonly id: Name; readonly name: Name; readonly kind: Kind; meta(): { id: Name; name: Name; kind: Kind } };`,
  `export type CdpCommandAlias<Params, Result, Name extends string> = ((params: Params) => Promise<Result>) & CdpNamedValue<Name, "command">;`,
  `export type CdpOptionalCommandAlias<Params, Result, Name extends string> = ((params?: Params) => Promise<Result>) & CdpNamedValue<Name, "command">;`,
  `export type CdpEventAlias<Payload, Name extends string> = z.ZodType<Payload> & CdpNamedValue<Name, "event">;`,
  `export type CdpAliasSend = (method: string, params?: unknown) => Promise<unknown>;`,
  `export type CdpAliasHooks = {`,
  `  onCustomCommand?: (name: string, params_schema?: z.ZodType | null, result_schema?: z.ZodType | null) => void;`,
  `  onCustomEvent?: (name: string, event_schema?: z.ZodType | null) => void;`,
  `};`,
  `export type ModCustomCommandConfig<TParamsSchema = unknown, TResultSchema = unknown> = {`,
  `  params_schema?: TParamsSchema | null;`,
  `  result_schema?: TResultSchema | null;`,
  `  expression?: string | null;`,
  `};`,
  `export type CdpCommandSpec<TParamsSchema extends z.ZodType = z.ZodType, TResultSchema extends z.ZodType = z.ZodType> = {`,
  `  params_schema?: TParamsSchema | null;`,
  `  result_schema?: TResultSchema | null;`,
  `  expression?: string | null;`,
  `};`,
  `export type CdpEventSpec<TEventSchema extends z.ZodType = z.ZodType> = { event_schema?: TEventSchema | null };`,
  `export type CdpCommandMap = Record<string, CdpCommandSpec>;`,
  `export type CdpEventMap = Record<string, CdpEventSpec>;`,
  ``,
  `type DomainName<TName extends string> = TName extends \`\${infer TDomain}.\${string}\` ? TDomain : never;`,
  `type MemberName<TName extends string> = TName extends \`\${string}.\${infer TMember}\` ? TMember : never;`,
  `type RequiredKeys<TValue> = TValue extends object ? { [TKey in keyof TValue]-?: {} extends Pick<TValue, TKey> ? never : TKey }[keyof TValue] : keyof TValue;`,
  `type HasRequiredParams<TParams> = TParams extends object ? [RequiredKeys<TParams>] extends [never] ? false : true : true;`,
  `type NativeCommandAliasSpec<TCommand> = TCommand extends { params: infer TParams extends z.ZodType; result: infer TResult extends z.ZodType } ? { params: z.input<TParams>; result: z.output<TResult> } : never;`,
  `type NativeEventAliasSpec<TEvent> = TEvent extends z.ZodType ? z.output<TEvent> : never;`,
  `type CustomCommandAliasSpec<TCommand extends CdpCommandSpec> = {`,
  `  params: TCommand["params_schema"] extends z.ZodType ? z.input<TCommand["params_schema"]> : ProtocolParams;`,
  `  result: TCommand["result_schema"] extends z.ZodType ? z.output<TCommand["result_schema"]> : ProtocolResult;`,
  `};`,
  `type CustomEventAliasSpec<TEvent extends CdpEventSpec> = TEvent["event_schema"] extends z.ZodType ? z.output<TEvent["event_schema"]> : ProtocolPayload;`,
  `type ModCommandBase = Extract<keyof typeof Mod, \`\${string}Params\`> extends infer TKey ? TKey extends \`\${infer TBase}Params\` ? \`\${TBase}Response\` extends keyof typeof Mod ? TBase : never : never : never;`,
  `type ModEventBase = Extract<keyof typeof Mod, \`\${string}Event\`> extends infer TKey ? TKey extends \`\${infer TBase}Event\` ? TBase : never : never;`,
  `type ModParamsSchema<TBase extends string> = Extract<(typeof Mod)[Extract<\`\${TBase}Params\`, keyof typeof Mod>], z.ZodType>;`,
  `type ModResponseSchema<TBase extends string> = Extract<(typeof Mod)[Extract<\`\${TBase}Response\`, keyof typeof Mod>], z.ZodType>;`,
  `type ModEventSchema<TBase extends string> = Extract<(typeof Mod)[Extract<\`\${TBase}Event\`, keyof typeof Mod>], z.ZodType>;`,
  `type NativeCommandAliasSpecs = { [TName in keyof typeof commands & string]: NativeCommandAliasSpec<(typeof commands)[TName]> };`,
  `type NativeEventAliasSpecs = { [TName in keyof typeof events & string]: NativeEventAliasSpec<(typeof events)[TName]> };`,
  `type ModCommandAliasSpecs = { [TBase in ModCommandBase as \`Mod.\${Uncapitalize<TBase>}\`]: { params: z.input<ModParamsSchema<TBase>>; result: z.output<ModResponseSchema<TBase>> } };`,
  `type ModEventAliasSpecs = { [TBase in ModEventBase as \`Mod.\${Uncapitalize<TBase>}\`]: z.output<ModEventSchema<TBase>> };`,
  `type CustomCommandAliasSpecs<TCommands extends CdpCommandMap> = { [TName in keyof TCommands & string]: CustomCommandAliasSpec<TCommands[TName]> };`,
  `type CustomEventAliasSpecs<TEvents extends CdpEventMap> = { [TName in keyof TEvents & string]: CustomEventAliasSpec<TEvents[TName]> };`,
  `type CommandAliasSpecs<TCommands extends CdpCommandMap> = NativeCommandAliasSpecs & ModCommandAliasSpecs & CustomCommandAliasSpecs<TCommands>;`,
  `type EventAliasSpecs<TEvents extends CdpEventMap> = NativeEventAliasSpecs & ModEventAliasSpecs & CustomEventAliasSpecs<TEvents>;`,
  `type CommandAlias<TSpec extends { params: unknown; result: unknown }, TName extends string> = HasRequiredParams<TSpec["params"]> extends true ? CdpCommandAlias<TSpec["params"], TSpec["result"], TName> : CdpOptionalCommandAlias<TSpec["params"], TSpec["result"], TName>;`,
  `type CommandAliases<TSpecs extends Record<string, { params: unknown; result: unknown }>> = {`,
  `  [TDomain in DomainName<Extract<keyof TSpecs, string>>]: {`,
  `    [TName in Extract<keyof TSpecs, \`\${TDomain}.\${string}\`> as MemberName<Extract<TName, string>>]: CommandAlias<TSpecs[TName], Extract<TName, string>>;`,
  `  };`,
  `};`,
  `type EventAliases<TSpecs extends Record<string, unknown>> = {`,
  `  [TDomain in DomainName<Extract<keyof TSpecs, string>>]: {`,
  `    [TName in Extract<keyof TSpecs, \`\${TDomain}.\${string}\`> as MemberName<Extract<TName, string>>]: CdpEventAlias<TSpecs[TName], Extract<TName, string>>;`,
  `  };`,
  `};`,
  `type MergeDomainAliases<TCommands extends CdpCommandMap, TEvents extends CdpEventMap> = {`,
  `  [TDomain in keyof (CommandAliases<CommandAliasSpecs<TCommands>> & EventAliases<EventAliasSpecs<TEvents>>)]:`,
  `    TDomain extends keyof CommandAliases<CommandAliasSpecs<TCommands>>`,
  `      ? TDomain extends keyof EventAliases<EventAliasSpecs<TEvents>>`,
  `        ? CommandAliases<CommandAliasSpecs<TCommands>>[TDomain] & EventAliases<EventAliasSpecs<TEvents>>[TDomain]`,
  `        : CommandAliases<CommandAliasSpecs<TCommands>>[TDomain]`,
  `      : TDomain extends keyof EventAliases<EventAliasSpecs<TEvents>>`,
  `        ? EventAliases<EventAliasSpecs<TEvents>>[TDomain]`,
  `        : never;`,
  `};`,
  `type ModAliasOverrides = {`,
  `  Mod: {`,
  `    addCustomCommand<TName extends string, TParamsSchema, TResultSchema>(name: TName, config?: ModCustomCommandConfig<TParamsSchema, TResultSchema>): Promise<z.output<typeof Mod.AddCustomCommandResponse>>;`,
  `    addCustomCommand(params: z.input<typeof Mod.AddCustomCommandParams>): Promise<z.output<typeof Mod.AddCustomCommandResponse>>;`,
  `    addCustomEvent<TName extends string, TEventSchema>(name: TName, config?: { event_schema?: TEventSchema | null }): Promise<z.output<typeof Mod.AddCustomEventResponse>>;`,
  `    addCustomEvent(params: z.input<typeof Mod.AddCustomEventParams>): Promise<z.output<typeof Mod.AddCustomEventResponse>>;`,
  `  };`,
  `};`,
  `export type CdpEventPayloads<TEvents extends CdpEventMap = {}> = EventAliasSpecs<TEvents>;`,
  `export type CdpCommandAliases<TCommands extends CdpCommandMap = {}> = CommandAliases<CommandAliasSpecs<TCommands>>;`,
  `export type CdpAliases<TCommands extends CdpCommandMap = {}, TEvents extends CdpEventMap = {}> = {`,
  `  readonly types: typeof runtimeTypes;`,
  `  readonly commands: typeof commands;`,
  `  readonly events: typeof events;`,
  `  readonly REQUEST: "request";`,
  `  readonly RESPONSE: "response";`,
  `  readonly EVENT: "event";`,
  `} & MergeDomainAliases<TCommands, TEvents> & ModAliasOverrides;`,
  ``,
  `function withCdpName<T extends object, Name extends string, Kind extends string>(value: T, id: Name, kind: Kind): T & CdpNamedValue<Name, Kind> {`,
  `  Object.defineProperties(value, {`,
  `    id: { value: id, enumerable: true, configurable: true },`,
  `    name: { value: id, configurable: true },`,
  `    kind: { value: kind, enumerable: true, configurable: true },`,
  `  });`,
  `  if (!("meta" in value)) Object.defineProperty(value, "meta", { value: () => ({ id, name: id, kind }), configurable: true });`,
  `  return value as T & CdpNamedValue<Name, Kind>;`,
  `}`,
  ``,
  `export function createCdpAliases(send: CdpAliasSend, hooks: CdpAliasHooks = {}): CdpAliases {`,
  `  return {`,
  `    types: runtimeTypes,`,
  `    commands,`,
  `    events,`,
  `    REQUEST: "request",`,
  `    RESPONSE: "response",`,
  `    EVENT: "event",`,
];
for (const d of domains) {
  if (!(d.commands || []).length && !(d.events || []).length) continue;
  aliases.push(`    ${word(d.domain)}: {`);
  for (const x of d.commands || []) {
    const commandName = `${d.domain}.${x.name}`;
    aliases.push(
      `      ${word(x.name)}: withCdpName(async (params?: cdp.types.ts.${d.domain}.${params(x.name)}) => commands[${JSON.stringify(commandName)}].result.parse(await send(${JSON.stringify(commandName)}, commands[${JSON.stringify(commandName)}].params.parse(params ?? {}))), ${JSON.stringify(commandName)}, "command"),`,
    );
  }
  for (const x of d.events || []) {
    const eventName = `${d.domain}.${x.name}`;
    aliases.push(
      `      ${word(x.name)}: withCdpName(events[${JSON.stringify(eventName)}], ${JSON.stringify(eventName)}, "event"),`,
    );
  }
  aliases.push(`    },`);
}
aliases.push(`    Mod: {`);
for (const base of modcdpTypes
  .filter((x) => x.name.endsWith("Params"))
  .map((x) => x.name.slice(0, -"Params".length))
  .filter((base) => modcdpTypes.some((x) => x.name === `${base}Response`))) {
  const methodName = base ? base[0].toLowerCase() + base.slice(1) : base;
  const commandName = `Mod.${methodName}`;
  const lines =
    base === "AddCustomCommand"
      ? [
          `      ${methodName}: withCdpName(async (params_or_name?: cdp.types.ts.Mod.${base}Params | string, config: ModCustomCommandConfig = {}) => {`,
          `        const input = typeof params_or_name === "string" ? { name: params_or_name, expression: config.expression ?? null, params_schema: config.params_schema ?? null, result_schema: config.result_schema ?? null } : params_or_name;`,
          `        const parsed = Mod.${base}Params.parse(input ?? {});`,
        ]
      : base === "AddCustomEvent"
        ? [
            `      ${methodName}: withCdpName(async (params_or_name?: cdp.types.ts.Mod.${base}Params | string, config: { event_schema?: z.ZodType | null } = {}) => {`,
            `        const input = typeof params_or_name === "string" ? { name: params_or_name, event_schema: config.event_schema ?? null } : params_or_name;`,
            `        const parsed = Mod.${base}Params.parse(input ?? {});`,
          ]
        : [
            `      ${methodName}: withCdpName(async (params?: cdp.types.ts.Mod.${base}Params) => {`,
            `        const parsed = Mod.${base}Params.parse(params ?? {});`,
          ];
  if (base === "AddCustomCommand") {
    lines.push(
      `        const name = normalizeModCDPName(parsed.name);`,
      `        const params_schema = validateZodSchema(parsed.params_schema);`,
      `        const result_schema = validateZodSchema(parsed.result_schema);`,
      `        const response = Mod.${base}Response.parse(await send(${JSON.stringify(commandName)}, { ...parsed, name }));`,
      `        hooks.onCustomCommand?.(name, params_schema, result_schema);`,
      `        return response;`,
    );
  } else if (base === "AddCustomEvent") {
    lines.push(
      `        const direct_schema = Mod.ZodType.safeParse(parsed);`,
      `        if (direct_schema.success) {`,
      `          const name = normalizeModCDPName(direct_schema.data);`,
      `          const event_schema = validateZodSchema(direct_schema.data);`,
      `          const response = Mod.${base}Response.parse(await send(${JSON.stringify(commandName)}, { name, event_schema }));`,
      `          hooks.onCustomEvent?.(name, event_schema);`,
      `          return response;`,
      `        }`,
      `        const object_params = Mod.AddCustomEventObjectParams.parse(parsed);`,
      `        const name = normalizeModCDPName(object_params.name);`,
      `        const event_schema = validateZodSchema(object_params.event_schema);`,
      `        const response = Mod.${base}Response.parse(await send(${JSON.stringify(commandName)}, { ...object_params, name, event_schema }));`,
      `        hooks.onCustomEvent?.(name, event_schema);`,
      `        return response;`,
    );
  } else if (base === "AddMiddleware") {
    lines.push(
      `        const name = parsed.name == null ? undefined : normalizeModCDPName(parsed.name);`,
      `        return Mod.${base}Response.parse(await send(${JSON.stringify(commandName)}, { ...parsed, name }));`,
    );
  } else {
    lines.push(`        return Mod.${base}Response.parse(await send(${JSON.stringify(commandName)}, parsed));`);
  }
  lines.push(`      }, ${JSON.stringify(commandName)}, "command"),`);
  aliases.push(...lines);
}
for (const base of modcdpTypes.filter((x) => x.name.endsWith("Event")).map((x) => x.name.slice(0, -"Event".length))) {
  const eventName = `Mod.${base ? base[0].toLowerCase() + base.slice(1) : base}`;
  aliases.push(
    `      ${base ? base[0].toLowerCase() + base.slice(1) : base}: withCdpName(Mod.${base}Event, ${JSON.stringify(eventName)}, "event"),`,
  );
}
aliases.push(`    },`, `  };`, `}`, ``);

const zod_dir = path.join(generated_dir, "zod");
fs.rmSync(zod_dir, { recursive: true, force: true });
fs.mkdirSync(zod_dir, { recursive: true });

const zod_helper = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `import type { z } from "zod";`,
  ``,
  `export type CdpNamedSchema<T extends z.ZodType> = T & { readonly id: string; readonly name: string; readonly kind: string; meta(): { id: string; name: string; kind: string } };`,
  `export type CdpCommandSchema<Params extends z.ZodType<Record<string, unknown>> = z.ZodType<Record<string, unknown>>, Result extends z.ZodType<Record<string, unknown>> = z.ZodType<Record<string, unknown>>, Name extends string = string> = { readonly id: Name; readonly name: Name; readonly kind: "command"; readonly params: Params; readonly result: Result; meta(): { id: Name; name: Name; kind: "command" } };`,
  `export const withCdpMeta = <T extends z.ZodType>(schema: T, id: string, kind: string, extra = {}): CdpNamedSchema<T> => {`,
  `  const meta = { id, name: id, kind, ...extra };`,
  `  const named = schema.meta(meta);`,
  `  Object.defineProperties(named, {`,
  `    id: { value: id, enumerable: true, configurable: true },`,
  `    name: { value: id, configurable: true },`,
  `    kind: { value: kind, enumerable: true, configurable: true },`,
  `  });`,
  `  return named as CdpNamedSchema<T>;`,
  `};`,
  `export const withCdpCommand = <Name extends string, Params extends z.ZodType<Record<string, unknown>>, Result extends z.ZodType<Record<string, unknown>>>(id: Name, params: Params, result: Result): CdpCommandSchema<Params, Result, Name> => {`,
  `  const meta = { id, name: id, kind: "command" as const };`,
  `  return {`,
  `    id,`,
  `    name: id,`,
  `    kind: "command",`,
  `    params,`,
  `    result,`,
  `    meta: () => meta,`,
  `  };`,
  `};`,
  ``,
];
fs.writeFileSync(path.join(zod_dir, "helpers.ts"), zod_helper.join("\n"));

for (const d of domains) {
  const refs = new Set<string>();
  for (const x of d.types || []) collect_refs(x, d.domain, refs);
  for (const x of d.commands || []) collect_refs(x, d.domain, refs);
  for (const x of d.events || []) collect_refs(x, d.domain, refs);

  const domain_zod = [
    `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
    `// @ts-nocheck -- recursive protocol schemas intentionally use lazy self/cross references.`,
    `import { z } from "zod";`,
    `import { withCdpCommand, withCdpMeta } from "./helpers.js";`,
  ];
  for (const ref of [...refs].sort())
    domain_zod.push(`import * as ${domain_file(ref)} from "./${domain_file(ref)}.js";`);
  domain_zod.push(``);

  for (const x of d.types || [])
    domain_zod.push(
      `export const ${local_name(x.id)} = withCdpMeta(${zexpr(x, d.domain)}, ${JSON.stringify(`${d.domain}.${x.id}`)}, "type");`,
    );
  for (const x of d.commands || []) {
    const commandName = `${d.domain}.${x.name}`;
    const paramsExpr =
      commandName === "CacheStorage.requestCacheNames"
        ? `${zobj(x.parameters || [], d.domain)}.refine((value) => [value.securityOrigin, value.storageKey, value.storageBucket].filter((item) => item !== undefined).length === 1, { message: "Exactly one of securityOrigin, storageKey, or storageBucket must be provided." })`
        : zobj(x.parameters || [], d.domain);
    domain_zod.push(
      `export const ${local_name(params(x.name))} = withCdpMeta(${paramsExpr}, ${JSON.stringify(`${commandName}.params`)}, "commandParams", { method: ${JSON.stringify(commandName)} });`,
    );
    domain_zod.push(
      `export const ${local_name(result(x.name))} = withCdpMeta(${zobj(x.returns || [], d.domain)}, ${JSON.stringify(`${commandName}.result`)}, "commandResult", { method: ${JSON.stringify(commandName)} });`,
    );
    domain_zod.push(
      `export const ${local_name(`${title(x.name)}Command`)} = withCdpCommand(${JSON.stringify(commandName)}, ${local_name(params(x.name))}, ${local_name(result(x.name))});`,
    );
  }
  for (const x of d.events || [])
    domain_zod.push(
      `export const ${local_name(event(x.name))} = withCdpMeta(${zobj(x.parameters || [], d.domain)}, ${JSON.stringify(`${d.domain}.${x.name}`)}, "event", { phase: "event" });`,
    );

  domain_zod.push(``, `export const zod = {`);
  for (const x of d.types || []) domain_zod.push(`  ${word(x.id)}: ${local_name(x.id)},`);
  for (const x of d.commands || [])
    domain_zod.push(
      `  ${word(params(x.name))}: ${local_name(params(x.name))},`,
      `  ${word(result(x.name))}: ${local_name(result(x.name))},`,
    );
  for (const x of d.events || []) domain_zod.push(`  ${word(event(x.name))}: ${local_name(event(x.name))},`);
  domain_zod.push(`} as const;`, `export const commands = {`);
  for (const x of d.commands || [])
    domain_zod.push(`  ${JSON.stringify(`${d.domain}.${x.name}`)}: ${local_name(`${title(x.name)}Command`)},`);
  domain_zod.push(`} as const;`, `export const events = {`);
  for (const x of d.events || [])
    domain_zod.push(`  ${JSON.stringify(`${d.domain}.${x.name}`)}: ${local_name(event(x.name))},`);
  domain_zod.push(
    `} as const;`,
    `export const types = { zod } as const;`,
    `export const cdp = { types, commands, events } as const;`,
    ``,
  );
  fs.writeFileSync(path.join(zod_dir, `${domain_file(d.domain)}.ts`), domain_zod.join("\n"));
}

const zod = [
  `// Generated by types/codegen.ts from devtools-protocol@${meta.version}. Do not edit by hand.`,
  `import { Mod } from "../modcdp.js";`,
];
for (const d of domains) zod.push(`import * as ${domain_file(d.domain)} from "./zod/${domain_file(d.domain)}.js";`);
zod.push(``, `export type CdpZodSchemas = {`, `  readonly Mod: typeof Mod;`);
for (const d of domains) zod.push(`  readonly ${word(d.domain)}: typeof ${domain_file(d.domain)}.zod;`);
zod.push(`};`, ``);
zod.push(`export type CdpCommandSchemas =`);
domains.forEach((d, index) => {
  const prefix = index === 0 ? `  ` : `  & `;
  zod.push(`${prefix}typeof ${domain_file(d.domain)}.commands${index === domains.length - 1 ? `;` : ``}`);
});
zod.push(``);
zod.push(`export type CdpEventSchemas =`);
domains.forEach((d, index) => {
  const prefix = index === 0 ? `  ` : `  & `;
  zod.push(`${prefix}typeof ${domain_file(d.domain)}.events${index === domains.length - 1 ? `;` : ``}`);
});
zod.push(
  ``,
  `export type CdpRuntimeTypes = { readonly zod: CdpZodSchemas };`,
  `export type CdpRuntime = {`,
  `  readonly types: CdpRuntimeTypes;`,
  `  readonly commands: CdpCommandSchemas;`,
  `  readonly events: CdpEventSchemas;`,
  `};`,
  ``,
  `export const zod: CdpZodSchemas = {`,
  `  Mod,`,
);
for (const d of domains) zod.push(`  ${word(d.domain)}: ${domain_file(d.domain)}.zod,`);
zod.push(`};`, `export const commands: CdpCommandSchemas = {`);
for (const d of domains) zod.push(`  ...${domain_file(d.domain)}.commands,`);
zod.push(`};`, `export const events: CdpEventSchemas = {`);
for (const d of domains) zod.push(`  ...${domain_file(d.domain)}.events,`);
zod.push(
  `};`,
  `export const types: CdpRuntimeTypes = { zod };`,
  `export const cdp: CdpRuntime = { types, commands, events };`,
  ``,
);

fs.mkdirSync(generated_dir, { recursive: true });
fs.writeFileSync(path.join(generated_dir, "cdp.ts"), cdp.join("\n"));
fs.writeFileSync(path.join(generated_dir, "zod.ts"), zod.join("\n"));
fs.writeFileSync(path.join(generated_dir, "aliases.ts"), aliases.join("\n"));
fs.rmSync(tmp, { recursive: true, force: true });
console.log(
  `Generated js/src/types/generated/cdp.ts, js/src/types/generated/zod.ts, js/src/types/generated/zod/*.ts, and js/src/types/generated/aliases.ts from devtools-protocol@${meta.version} (${domains.length} domains).`,
);
